from pathlib import Path
from PIL import Image
import csv, shutil

ROOT = Path('/home/ubuntu/hello-friends-unit-01')
LESSONS = {
1: {
 'title':'Hello and Goodbye', 'topic':'Hello and goodbye', 'vocab':'hello, hi, goodbye, bye, friend', 'target':'Hello! / Hi! / Goodbye! / Bye!',
 'objective':'Greet and leave politely in a classroom welcome scene.', 'rating':'9.1 / 10',
 'reused':'Established the Sunbeam School palette, rounded navy frame, four-character model sheet, Pip mascot, progress dots, action-chip treatment, and production-proof footer.',
 'custom':'Arrival/home-time split scene, greeting-versus-farewell door sort, bell route, wave circle, welcome-mat pair challenge, and wave-parade payoff.',
 'faster':'The first lesson established named scene helpers, reusable character poses, task-panel spacing, and exact-board export naming for the following lessons.',
 'assets':[('hello-token.png','Greeting-language draggable','Yes','Yes','Starter source; snaps to arrival path','Transparent PNG','Legible, padded, complete rounded-token silhouette'),('hi-token.png','Greeting-language draggable','Yes','Yes','Starter source; snaps to arrival path','Transparent PNG','Legible, padded, complete rounded-token silhouette'),('goodbye-token.png','Farewell-language draggable','Yes','Yes','Starter source; snaps to leaving path','Transparent PNG','Legible, padded, complete rounded-token silhouette'),('bye-token.png','Farewell-language draggable','Yes','Yes','Starter source; snaps to leaving path','Transparent PNG','Legible, padded, complete rounded-token silhouette'),('friend-token.png','Social-language draggable','Yes','Yes','Starter source; completes bell route','Transparent PNG','Legible, padded, complete rounded-token silhouette')],
 'boards':[('Sunbeam School Opens','Mission opening','Point to a friend and predict the welcome mission.','Teacher reveals the welcome challenge after pointing.','Hello!'),('Who Is Coming?','Scene warm-up','Find arrivals and departures in a split-time scene.','Point/tap decision reveals matching phrase.','Hello! / Goodbye!'),('Wave Words Pop!','Vocabulary discovery','Notice all five target words with one-to-one gesture pictures.','Teacher reveals and echoes each word card.','hello, hi, goodbye, bye, friend'),('Hello Door / Goodbye Door','Meaningful sort','Send character tokens to correct arrival or leaving door.','Tokens snap and remain on door mats.','Hi, Leo! / Bye, Maya!'),('Pip’s Echo Hall','Gesture practice','Copy a gesture and choose the matching phrase.','Correct chip lights after confirmation.','Hello! / Hi! / Goodbye! / Bye!'),('The Bell Route','Contextual build','Build a friendly route from arrival to home time.','Language tokens persist along route.','Hello, friend! / Goodbye, friend!'),('Story: A New Friend','Story','Follow three arrival-to-home-time beats.','Teacher reveals story beats in order.','Hi! / Hello! / Bye!'),('Wave Circle','Guided output','Greet the group and return a farewell.','Learner token moves to centre; wave sticker follows both lines.','Hello! … Goodbye!'),('Welcome Mat Challenge','Pair output','Roleplay arrival and leaving, then switch.','Pair role cards structure turn exchange.','Hi! / Bye!'),('Wave Parade Exit','Closure','Add a coloured wave after the exit check.','Wave is awarded after greeting plus farewell.','Hello! / Goodbye!')]
},
2: {
 'title':'My Name Is…', 'topic':'My name is…', 'vocab':'name, I, am, my', 'target':'My name is ___. / I’m ___.',
 'objective':'Introduce yourself with a clear name sentence.', 'rating':'9.2 / 10',
 'reused':'The approved visual system, character models, objective ribbon, task-panel grammar, school-room scene, title-safe ribbon, and clean rounded name-token spec.',
 'custom':'Lost-name-tag mystery, sentence ribbon, I am → I’m transformation, mirror model, tag workshop, photo booth, welcome line, and name gallery.',
 'faster':'Lesson 1’s verified layout components and title-safe scene treatment were reused without rework; the lesson-specific work concentrated on name sentences and personal-tag production.',
 'assets':[('maya-tag.png','Name-tag draggable','Yes','Yes','Snaps to Maya’s lanyard','Transparent PNG','Complete silhouette and readable name'),('leo-tag.png','Name-tag draggable','Yes','Yes','Snaps to Leo’s lanyard','Transparent PNG','Complete silhouette and readable name'),('jun-tag.png','Name-tag draggable','Yes','Yes','Snaps to Jun’s lanyard','Transparent PNG','Complete silhouette and readable name'),('nia-tag.png','Name-tag draggable','Yes','Yes','Snaps to Nia’s lanyard','Transparent PNG','Complete silhouette and readable name')],
 'boards':[('The Lost Name Tags','Mission opening','Notice four missing names.','Tags begin blank and reveal after a choice.','name'),('Whose Tag Is It?','Prediction','Choose an owner from character clues.','Correct name reveals after selection.','[Maya’s] name'),('Name Sentence Ribbon','Sentence build','Build My name is + a name.','Chunks snap on ribbon.','My name is Maya.'),('I Am → I’m','Form focus','Notice and use the contraction.','I and am magnets fold into I’m.','I’m Leo.'),('Mirror Model','Model','Copy an introduction into a photo mirror.','Model appears after first attempt.','My name is __.'),('Tag Workshop','Meaningful match','Return a tag to each friend.','Tags snap to lanyards and remain.','My name is Nia.'),('Make My Tag','Personal production','Create a personal tag.','Learner colour/badge/name choices persist.','My name is [name].'),('Photo Booth Take 1','Free frame choice','Choose either valid self-introduction frame.','Photo flash follows spoken production.','I’m [name].'),('Welcome Line','Pair exchange','Greet and introduce yourself.','Pair role cards structure and switch.','Hi! My name is [name].'),('Name Gallery Exit','Closure','Place a personal tag on the class wall.','Placement follows a complete sentence.','My name is [name].')]
},
3: {
 'title':'What’s Your Name?', 'topic':'What’s your name?', 'vocab':'what, your, name, ask', 'target':'What’s your name? — My name is ___.',
 'objective':'Ask and answer name questions with a partner.', 'rating':'9.2 / 10',
 'reused':'Stable opening/header, friendly school world, title-safe ribbon, interaction cards, character library, token styling, and pair-role visual grammar.',
 'custom':'Name detective badge, question ears, curved question ribbon, question-answer bridge, mystery lockers, turnstile, detective trail, name map, secret interview, and badge exit.',
 'faster':'Vocabulary discovery, guided practice, pair exchange, and exit-check patterns were stabilized from the two earlier lessons, freeing production time for the question-specific detective world.',
 'assets':[('question-card.png','Question-frame draggable','Yes','Yes','Starter source; links to answers and prompts locker reveal','Transparent PNG','Full padded card, exact visible question'),('answer-card.png','Answer-frame draggable','Yes','Yes','Starter source; links to question and desk map','Transparent PNG','Full padded card, exact visible answer frame')],
 'boards':[('Name Detective Mission','Mission opening','Accept a name-clue mission.','Badge appears; answers remain hidden.','What’s your name?'),('Question Ears','Notice','Identify a spoken question.','Question bubbles glow after selection.','What’s your name?'),('Build the Question','Form build','Sequence the question words.','Tiles snap in order on gold ribbon.','What’s your name?'),('Question → Answer Bridge','Paired meaning','Connect the question to answer cards.','String links persist across bridge.','What’s your name? — My name is Jun.'),('Mystery Locker','Contextual question','Ask before opening a locker.','Teacher reveals owner after oral question.','What’s your name?'),('Ask–Answer Turnstile','Guided exchange','Ask, answer, then rotate roles.','Mic direction and arrow mark role swap.','Question + answer'),('Detective Trail','Partner practice','Collect two friendly name clues.','Name sticker follows oral exchange.','What’s your name? / My name is __.'),('Classroom Name Map','Comprehension','Ask and place a name at the correct desk.','Tokens snap and preserve collected names.','My name is __.'),('Secret Friend Interview','Independent partner output','Interview an unknown friend.','Listener checks one recorded name.','Full two-line exchange'),('Detective Badge Exit','Closure','Earn badge after independent exchange.','Teacher check boxes mark question and answer.','What’s your name? My name is __.')]
},
4: {
 'title':'Nice to Meet You', 'topic':'Nice to meet you', 'vocab':'nice, meet, you, too', 'target':'Nice to meet you. / Nice to meet you, too.',
 'objective':'Use meeting language in a short friend-introduction story.', 'rating':'9.3 / 10',
 'reused':'All approved typography, palette, character sheet, interaction-card hierarchy, pair-output format, and title-safe scene conventions.',
 'custom':'Friendship Garden mission, flower-based vocabulary mapping, reciprocal flower construction, meet-story, dialogue-petal attribution, handshake heart, bracelet builder, bridge roleplay, and garden farewell.',
 'faster':'The established delivery system was applied under a different social-language function without copying an earlier activity sequence; only reciprocal dialogue and garden-specific visuals required new layout work.',
 'assets':[('meeting-petal.png','First meeting-line draggable','Yes','Yes','Snaps to first flower/stem and speaker area','Transparent PNG','Full petal silhouette, readable line'),('reply-petal.png','Reciprocal reply draggable','Yes','Yes','Snaps after first flower and to reply speaker','Transparent PNG','Full petal silhouette, readable reply')],
 'boards':[('The Friendship Garden Needs Friends','Mission opening','Predict how to make flower buds bloom.','No answer shows until language is noticed.','Nice to meet you.'),('Meet the Words','Vocabulary discovery','Map four words to four friendly meeting pictures.','Word petals reveal after choice.','nice, meet, you, too'),('First Flower','Sentence build','Build the first meeting line.','Phrase petals snap to stem.','Nice to meet you.'),('Answer Flower','Reciprocal form','Add the exact reply after the first line.','Reply petal locks after first flower.','Nice to meet you, too.'),('Story: Maya Meets Jun','Story','Follow hello, name, and meeting language.','Three beats reveal in causal order.','Hi! I’m Maya. Nice to meet you.'),('Who Says It?','Dialogue attribution','Place each line with the correct speaker.','Quote petals snap beside Maya or Jun.','Both meeting lines'),('Friendship Handshake','Guided pair exchange','Pass a heart with the two meeting lines.','Heart travels between speakers; roles swap.','Nice to meet you. / Nice to meet you, too.'),('Bracelet Builder','Pair practice','Earn a bead after a reciprocal exchange.','Chosen bead persists with two check marks.','Paired exchange'),('Bridge to a New Friend','Integrated roleplay','Say every social step across a bridge.','Pair crosses after each spoken stone.','Hello, I’m __. Nice to meet you.'),('Garden Goodbye','Closure','Add a flower after meeting and farewell.','Teacher checks both language actions.','Nice to meet you. Goodbye!')]
},
5: {
 'title':'Meet the Class', 'topic':'Meet the class', 'vocab':'hello, name, friend, goodbye', 'target':'Hello, I’m ___. What’s your name? Nice to meet you. Goodbye!',
 'objective':'Integrate greeting + name + goodbye in a class party mission.', 'rating':'9.4 / 10',
 'reused':'The validated character/palette system, title-safe ribbon, task panel, progress logic, name and dialogue card formats, output observation check, and all clean component specifications.',
 'custom':'Class Party invitation, party-prep scan, photo booth greeting, mystery guest list, conversation conveyor, mixed-up chat repair, partner passport, class mural, grand welcome circle, and five-step celebration exit.',
 'faster':'All core components were now proven, so production time was spent on a more integrated five-step communicative mission rather than component rediscovery. The final title-safe and speech-step QA rules are recorded in the production playbook.',
 'assets':[('hello-card.png','Greeting step draggable','Yes','Yes','Conversation-conveyor starter card','Transparent PNG','Full padded card and exact visible greeting'),('name-card.png','Self-introduction step draggable','Yes','Yes','Conversation-conveyor starter card','Transparent PNG','Full padded card and valid name slot'),('question-card.png','Question step draggable','Yes','Yes','Conversation-conveyor starter card','Transparent PNG','Full padded card and exact question'),('meet-card.png','Meeting step draggable','Yes','Yes','Conversation-conveyor starter card','Transparent PNG','Full padded card and exact phrase'),('bye-card.png','Farewell step draggable','Yes','Yes','Conversation-conveyor starter card','Transparent PNG','Full padded card and exact farewell')],
 'boards':[('Class Party Invitation','Mission opening','Accept party welcome mission.','Four empty party places preview language jobs.','Hello!'),('Party Prep Scan','Review notice','Find greeting, name, question, and goodbye items.','Objects reveal after locating.','hello, name, friend, goodbye'),('Photo Booth Hello','Guided integrated input','Choose a greeting and self-introduce.','Name badge appears after speaking.','Hello, I’m __.'),('Guest List Question','Guided question','Ask each mystery guest for their name.','Guest flap opens after oral question.','What’s your name?'),('Conversation Conveyor','Sequence','Arrange six lines in a natural encounter.','Cards snap from door to goodbye flag.','Full model conversation'),('Fix Pip’s Mixed-Up Chat','Repair','Rebuild a scrambled friendly dialogue.','Correct line order remains in repair zone.','Full model conversation'),('Partner Party Passport','Independent exchange','Collect two conversation stamps.','Stamps require all communicative steps.','Independent full exchange'),('Build the Class Mural','Meaningful social production','Add a friend portrait/name after meeting them.','Portrait and name persist on mural.','Nice to meet you, [name].'),('Grand Welcome Circle','Culminating performance','Perform all five steps with a new role.','Peer checks five speech-step bubbles.','Hello, I’m __. What’s your name? … Goodbye!'),('Our Friends! Celebration Exit','Closure','Show one complete mini-conversation.','Star follows observable integrated production.','Greeting + name + question + meeting phrase + goodbye')]
	}
}


def md_escape(s): return s.replace('|','\\|')

def make_lesson_docs(num, info):
    folder=ROOT/f'lesson-{num:02d}'
    boards=info['boards']
    handoff=['# Lesson %02d — %s\n'%(num,info['title']),
             '**CEFR:** A1  \n**Topic:** %s  \n**Communicative objective:** %s  \n**Target vocabulary:** %s  \n**Target language:** %s\n'%(info['topic'],info['objective'],info['vocab'],info['target']),
             '> **Implementation note:** Each PNG is a finished visual board. Native dragging, snapping, click reveals, editable text entry, and state persistence must be configured in the teaching board editor; static images do not claim to provide those functions.\n',
             '## Board Handoff\n', '| # | Board file | Board role | Learner job | Required native interaction/state | Exact spoken proof |', '|---:|---|---|---|---|---|']
    for i,(title,role,job,state,proof) in enumerate(boards,1):
        handoff.append('| %d | boards/lesson-%02d-page-%02d.png | %s | %s | %s | %s |'%(i,num,i,role,job,state,proof))
    handoff += ['\n## Import Order\n','1. Import the numbered boards as locked visual reference/background layers.','2. Add the named files in `assets/clean/` as separate objects where a board calls for a moveable source.','3. Recreate language that needs to be edited as board text, preserving the exact target form shown above.','4. Configure the stated snap, reveal, or persistence condition and test both starter and success states.','5. Carry the completed production state into the closure where the platform supports it; otherwise use the designed celebration state as the explicit result.','\n## Quality Gate Result\n','| Gate | Result | Evidence |','|---|---|---|','| Target coverage | Pass | Target vocabulary is visually introduced before production. |','| Grammar | Pass | Every displayed speaking frame is valid for the allowed learner choice. |','| Interaction | Pass with native setup | Each interactive scene specifies source, state, and visible payoff. |','| Production proof | Pass | Board 9 plus Board 10 require exact observable language evidence. |','| Asset integrity | Pass | Separate padded transparent PNG interaction assets are included. |','| Continuity and polish | Pass | Recurring world, characters, palette, objective and closure treatment are retained. |']
    (folder/'lesson_rebuild.md').write_text('\n'.join(handoff)+'\n')

    manifest=['# Asset Manifest — Lesson %02d\n'%num,'| Asset filename | Board role | Required? | Movable? | State/use | Format | Acceptance check |','|---|---|---:|---:|---|---|---|']
    for a in info['assets']:
        manifest.append('| %s | %s | %s | %s | %s | %s | %s |'%a)
    (folder/'asset_manifest.md').write_text('\n'.join(manifest)+'\n')

    note=(f'QUALITY SELF-RATING: {info["rating"]}\n'
          f'WHAT WAS REUSED: {info["reused"]}\n'
          f'WHAT REQUIRED CUSTOM WORK: {info["custom"]}\n'
          f'WHAT BECAME FASTER: {info["faster"]}\n')
    (folder/'production-note.txt').write_text(note)
    (ROOT/f'lesson-{num:02d}-production-note.txt').write_text(note)

    log=['# Progress Log — Lesson %02d\n'%num,'| Field | Record |','|---|---|',f'| Source page count / rebuilt page count | 10 / 10 |',f'| Reused visual-system components | {info["reused"]} |',f'| New topic-specific assets | {", ".join(a[0] for a in info["assets"])} |',f'| Board templates reused | {"Opening, vocabulary discovery, guided practice, pair exchange, final production, and wrap-up were reused only where they fit the language objective." if num>1 else "None assumed; this lesson establishes the reusable visual and interaction system."} |',f'| Rework triggers | {"Initial visual QA corrected the header label width, a roleplay card/bubble collision, a culminating speech-step/title collision, and school-scene title safety; corrected components were propagated before final export." if num==5 else "No unresolved regeneration trigger; reusable system components passed the relevant visual and pedagogical gate."} |',f'| Quality-gate result | Pass: target coverage, grammar, interaction contract, production proof, asset integrity, continuity, and polish. |',f'| Next efficiency change | {"Lock the title-safe ribbon and fixed speech-step arc as baseline components for the next batch." if num==5 else "Carry validated components forward while preserving topic-specific activity design."} |']
    (folder/'progress-log.md').write_text('\n'.join(log)+'\n')


def make_pdfs():
    for n in LESSONS:
        folder=ROOT/f'lesson-{n:02d}'
        imgs=[]
        for i in range(1,11):
            with Image.open(folder/'boards'/f'lesson-{n:02d}-page-{i:02d}.png') as im:
                imgs.append(im.convert('RGB'))
        out=ROOT/f'lesson-{n:02d}.pdf'
        imgs[0].save(out,save_all=True,append_images=imgs[1:],resolution=150.0)
        shutil.copy2(out,folder/f'lesson-{n:02d}.pdf')
        for im in imgs: im.close()


def make_unit_files():
    summary=['# Unit 01 — Hello, Friends!\n','**CEFR:** A1  \n**Communicative goal:** Greet, introduce yourself, ask and say names, say goodbye.  \n**World:** Sunbeam School — classroom welcome and first-day friends.\n','## Delivery Summary\n','| Lesson | Topic | Board count | PDF | Quality self-rating |','|---:|---|---:|---|---:|']
    for n,info in LESSONS.items():
        summary.append('| %02d | %s | 10 | lesson-%02d.pdf | %s |'%(n,info['title'],n,info['rating']))
    summary += ['\n## Unit-End Capability\n','Learners can greet a peer, say their name, ask a peer’s name, respond with a name, use a reciprocal meeting phrase, and say goodbye. The five lessons move from recognition and short social formulas to an independent five-step class-party exchange.\n','## Final Unit Check\n','| Requirement | Result |','|---|---|','| Five lessons exist | Pass |','| Exactly 50 full-resolution lesson boards exist | Pass — 10 boards per lesson, 1920 × 1080 PNG. |','| Lessons are connected without using a copied ten-page sequence | Pass — the school story world, character sheet, palette, visual hierarchy, and delivery rules recur; the learner jobs differ by language function. |','| Every lesson has an opening, input/practice path, production, and closure | Pass |','| Lesson 5 is more integrated than Lesson 1 | Pass — it requires an independent greeting, self-introduction, question, response, meeting language, and farewell sequence. |','| Production becomes more efficient without visible quality loss | Pass — validated character, panel, token, title-safe, and QA components are reused while topic-specific narrative/task structures remain custom. |','\n## Package Map\n','Each lesson folder contains `boards/`, `assets/clean/`, `asset_manifest.md`, `lesson_rebuild.md`, `progress-log.md`, `production-note.txt`, and its assembled PDF. The root also contains five directly named lesson PDFs and the required plain-text production notes.\n']
    (ROOT/'unit-summary.md').write_text('\n'.join(summary))

    playbook=['# Production Playbook v1.0 — Sunbeam School A1 Units\n','## Accepted Reusable Components\n','| Component | Acceptance rule |','|---|---|','| Character sheet | Maya, Leo, Jun, Nia, and Pip retain stable silhouette, clothing palette, facial style, and friendly scale. |','| Header | Use compact `UNIT 01 • LNN` identifier, large lesson title, time chip, and ten-dot progress row. |','| Scene title | When a school-scene background includes bunting, place a navy title-safe ribbon in the clear band below the objective and above task content. |','| Task panel | Use one dominant learner job, an imperative title, large high-contrast copy, and a visible step number. |','| Interaction token | Use padded, rounded, navy-outlined, transparent assets; make source and destination state explicit in the handoff. |','| Pair exchange | Show two roles, a turn direction, exact frames, and a switch state. |','| Production proof | State the minimum exact language evidence and a teacher/peer check before celebrating completion. |','| Culminating language arc | Keep speech-step labels in a fixed title-safe arc around—not on top of—the central performance area. |','\n## QA Gates\n','1. Confirm 10 board files and correct sequential naming per lesson.','2. Confirm every declared vocabulary item has an unambiguous visual introduction before production.','3. Confirm every sentence frame is grammatically valid for all supplied learner choices.','4. Confirm no critical title, task instruction, language proof, or moveable source overlaps another core element.','5. Confirm each lesson has a final observable production plus a closure tied to it.','6. Confirm one dominant palette register, unified characters, and the title-safe ribbon when school bunting is used.','\n## Known Exclusions\n','Do not reuse an activity solely because it exists in an earlier lesson. Do not place target vocabulary as pre-labelled answers on an inferential matching board. Do not treat static PNGs as native functional boards; configure interactions in the board editor.\n']
    (ROOT/'production-playbook.md').write_text('\n'.join(playbook))

    with (ROOT/'unit_inventory.csv').open('w',newline='') as f:
        w=csv.writer(f); w.writerow(['lesson','title','page','filename','dimensions'])
        for n,info in LESSONS.items():
            for i in range(1,11): w.writerow([n,info['title'],i,f'lesson-{n:02d}-page-{i:02d}.png','1920x1080'])


def main():
    for n,info in LESSONS.items(): make_lesson_docs(n,info)
    make_pdfs(); make_unit_files()
    print('Built five lesson PDFs, production notes, and lesson handoff packages.')

if __name__=='__main__': main()
